name: New Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        IMAGE_TAG=bexy:$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: List Docker images
      run: docker images

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the Docker image
      run: |
        docker tag ${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/bexy:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/bexy:latest
