name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and Push Docker image
      run: |
        docker tag my-image-name:$(date +%s) ${{ secrets.DOCKERHUB_USERNAME }}/$(basename ${{ github.repository }}):latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/$(basename ${{ github.repository }}):latest
